
/*Insert para la Tabla CLientes*/
INSERT INTO CLIENTE (ID, NIT, NOMBRES, APELLIDOS, TELEFONO, GENERO) VALUES (1, '1065639582', 'Amilkar Jose', 'Hernandez Oñate','30064490898','Masculino');
INSERT INTO CLIENTE (ID, NIT, NOMBRES, APELLIDOS, TELEFONO, GENERO) VALUES (2, '1006537488', 'Roberto Jose', 'Mangar Jimenez','3007664356','Masculino');
INSERT INTO CLIENTE (ID, NIT, NOMBRES, APELLIDOS, TELEFONO, GENERO) VALUES (3, '6654445678', 'Camilo Jose', 'Uribe Jimenez','3217762737','Masculino');


/*Insert para la Tabla Categorias*/
INSERT INTO CATEGORIA (ID, DESCRIPCION) VALUES (1, 'CAMISETAS');
INSERT INTO CATEGORIA (ID, DESCRIPCION) VALUES (2, 'COMICS');
INSERT INTO CATEGORIA (ID, DESCRIPCION) VALUES (3, 'VASOS');
INSERT INTO CATEGORIA (ID, DESCRIPCION) VALUES (4, 'JUGUETES');
INSERT INTO CATEGORIA (ID, DESCRIPCION) VALUES (5, 'ACCESORIOS');

/*Insert para la Tabla Productos*/
INSERT INTO PRODUCTO (ID, SERIAL, DESCRIPCION, STOCK, VALOR_UNITARIO, CATEGORIA_ID) VALUES (1, '001','camisa s', 20, 23000, 1);
INSERT INTO PRODUCTO (ID, SERIAL,DESCRIPCION, STOCK, VALOR_UNITARIO, CATEGORIA_ID) VALUES (2, '002','camisa m', 20, 24000, 1);
INSERT INTO PRODUCTO (ID, SERIAL,DESCRIPCION, STOCK, VALOR_UNITARIO, CATEGORIA_ID) VALUES (3,'003','camisa l', 20, 24500, 1);
INSERT INTO PRODUCTO (ID, SERIAL,DESCRIPCION, STOCK, VALOR_UNITARIO, CATEGORIA_ID) VALUES (4,'004','vaso Hulk', 1, 24500, 1);

/*Insert para la Tabla Facturas*/
INSERT INTO FACTURAS (FECHA, CLIENTE_ID) VALUES(NOW(), 1);
INSERT INTO FACTURAS (FECHA, CLIENTE_ID) VALUES(NOW(), 2);

/*Insert para la Tabla Items Facturas*/
INSERT INTO facturas_items (cantidad, factura_id, producto_id) VALUES(1, 1, 1);
INSERT INTO facturas_items (cantidad, factura_id, producto_id) VALUES(2, 1, 2);
INSERT INTO facturas_items (cantidad, factura_id, producto_id) VALUES(1, 2, 2);
INSERT INTO facturas_items (cantidad, factura_id, producto_id) VALUES(1, 2, 3);

